### ISSUE TITLE
utility name is inconsistant: `shig` or `ssign`

### ISSUE THREAD

**Issue by flosnvjx** [SierraSoftworks/shig#5]
Greetings,

Found this handy utility yesterday, is a very handy utility :)

A small UX issue that I realized is: the `--help` and diagnose message declare this utility as `ssign`, but the go package name (`go install`), repository name, and README file all use `shig` as utility name instead.  I think it'd be better to keep them consistant.

(IMO, the name `ssign` is more rememberable than `shig`, though both namespace are seemingly unused on repology.org and hence likely safe to use if distribution packaging is a goal)

https://repology.org/project/ssign/versions
https://repology.org/project/shig/versions

**Comment by notheotherben** [comment]
Thank you for the heads up - I've refactored all of these to match the repo name.
